[project]
name = "charlie"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=2.14.0",
    "rich>=14.2.0",
    "textual>=0.80.0",
]
